# Generated by Django 5.2 on 2026-07-10 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_time', models.DateTimeField()),
                ('close_time', models.DateTimeField(blank=True, null=True)),
                ('active_time', models.DateTimeField(blank=True, null=True)),
                ('open_price', models.FloatField()),
                ('close_price', models.FloatField()),
                ('position_side', models.CharField(choices=[('LONG', 'Long'), ('SHORT', 'Short')], max_length=10)),
                ('position_type', models.CharField(choices=[('MARKET', 'Market'), ('LIMIT', 'Limit'), ('STOP', 'Stop')], max_length=10)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
